# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b56810427052b8bd9f52cb098fe9d9d4b773f49d8516e7f9881f0d40b1eb4eb23e3099d96073beadfbc35e0a8e85ca2524701cb27995d46b4a9f9df508322dc

test:
  secret_key_base: 53762cf30c3e5e0d888432b528751e907a048c61298fc8ec1fce285d1fe717f2358219249e4c986cd69d7df568f7cc6489129b16a83b442673bd5397238310e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
